pullrequests:
  config:
  tasks:
    - id: lint-nodejs
    - id: unit-tests-nodejs
    - id: pr-standards
      config:
        prMilestoneCheck: true
branches:
  master:
    config:
    tasks:
      - id: unit-tests-nodejs
releases:
  published:
    tasks:
      - id: release-notes
      - id: npm-publish